import os
from github import Github
from dotenv import load_dotenv
import subprocess
import datetime

load_dotenv()

GITHUB_TOKEN = os.getenv("GITHUB_TOKEN")
USERNAME = os.getenv("GITHUB_USERNAME")
REPO_NAME = os.getenv("REPO_NAME")

def create_pr(branch_name, title, body):
    g = Github(GITHUB_TOKEN)
    repo = g.get_repo(f"{USERNAME}/{REPO_NAME}")

    repo.create_pull(
        title=title,
        body=body,
        head=branch_name,
        base="main"
    )


def git(cmd):
    subprocess.run(cmd, check=True)


def create_fix_pr(fixed_code):
    branch = f"ai-fix-{datetime.datetime.now().strftime('%Y%m%d%H%M%S')}"

    git(["git", "checkout", "-b", branch])

    with open("buggy_code.py", "w") as f:
        f.write(fixed_code)

    git(["git", "add", "buggy_code.py"])
    git(["git", "commit", "-m", "AI self-healing fix"])
    git(["git", "push", "-u", "origin", branch])

    create_pr(
        branch_name=branch,
        title="AI Self-Healing Fix",
        body="Automated fix generated by self-healing AI system."
    )

    git(["git", "checkout", "main"])
